// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlawgmmxzguedfzqcuxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYXdnbW14emd1ZWRmenFjdXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODY1ODYsImV4cCI6MjA3MTE2MjU4Nn0.DK5y_66i-oXWb7eRgXPhmJvldYp1a_Fhr0SiEJfCSbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});